
# For development, explicitly disabling email confirmation
project_id = "weiagpwgfmyjdglfpbeu"

[auth]
site_url = "http://localhost:3000"
# Explicitly disable email confirmation for development
enable_confirmations = false

