
project_id = "weiagpwgfmyjdglfpbeu"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[storage]
enabled = true

[auth]
enabled = true

[functions]
[functions.process-video]
verify_jwt = true
[functions.ask-video-ai]
verify_jwt = true
