
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://weiagpwgfmyjdglfpbeu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlaWFncHdnZm15amRnbGZwYmV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MTQ0MTUsImV4cCI6MjA2MjE5MDQxNX0.mT1XfP87DD0zs85mTxWaSWe7F7DHbLCZzddSh0vnRHY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Function to ensure the certificates table exists
export const setupCertificatesTable = async () => {
  try {
    // Call RPC function to create the certificates table if it doesn't exist
    const { data, error } = await supabase.rpc('create_certificates_table');
    
    if (error) {
      console.error("Error ensuring certificates table exists:", error);
    }
  } catch (e) {
    console.error("Error checking/creating certificates table:", e);
  }
};

// Initialize tables when the app starts
setupCertificatesTable();
